#!/bin/bash
set -e

cat /stopwords.txt << EOF
the
be
and
of
a
in
to
have
to
it
I
that
for
you
he
with
on
do
say
this
they
at
but
we
his
from
that
not
by
or
as
what
go
their
can
who
get
if
would
all
my
will
as
up
there
so
its
us
in
on
EOF

cat /etc/mysql/conf.d/phabricator.cnf << EOF
[mysqld]
max_allowed_packet = 100M
sql_mode=STRICT_ALL_TABLES
ft_stopword_file=/stopwords.txt
ft_min_word_len=3
ft_boolean_syntax=' |-><()~*:""&^'
innodb_buffer_pool_size=512M
EOF